sudo: required
services:
    - docker

install:
    - docker --version
script:
    - ./build.sh
after_success:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push 4oranges/dubuntu

