sudo: required
services:
    - docker

install:
    - docker --version
script:
    - docker-compose build --force-rm
after_success:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_USERNAME/dubuntu
